INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('1', 'Atlante', 'Hallut', 'ahallut0@yelp.com', '3554 Twin Pines Drive');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('2', 'Querida', 'Trahar', 'qtrahar1@alexa.com', '488 Emmet Trail');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('3', 'Earl', 'Dumbellow', 'edumbellow2@kickstarter.com', '94 Grayhawk Trail');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('4', 'Penny', 'Challener', 'pchallener3@wordpress.org', '88031 Carpenter Crossing');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('5', 'Christel', 'Vidyapin', 'cvidyapin4@java.com', '542 Karstens Parkway');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('6', 'Krystalle', 'Cardozo', 'kcardozo5@examiner.com', '4066 Meadow Valley Junction');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('7', 'Robers', 'Charteris', 'rcharteris6@boston.com', '154 Hanover Park');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('8', 'Morris', 'McNeish', 'mmcneish7@hexun.com', '9 Shoshone Hill');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('9', 'Arlina', 'Maliphant', 'amaliphant8@imageshack.us', '818 Kipling Park');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('10', 'Miof mela', 'Wroth', 'mwroth9@vimeo.com', '80 4th Circle');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('11', 'Kassi', 'Jobern', 'kjoberna@dot.gov', '998 1st Drive');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('12', 'Ysabel', 'Keech', 'ykeechb@blog.com', '30 East Point');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('13', 'Orelia', 'Evert', 'oevertc@vistaprint.com', '6 Hanson Pass');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('14', 'Lira', 'Drache', 'ldrached@sakura.ne.jp', '4804 Melvin Circle');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('15', 'Jan', 'Chiplen', 'jchiplene@pen.io', '4 Ruskin Court');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('16', 'Sharlene', 'Gingle', 'sginglef@blogtalkradio.com', '9409 Linden Way');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('17', 'Clemmy', 'Cooley', 'ccooleyg@nbcnews.com', '2050 Towne Park');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('18', 'Leighton', 'Ellesworthe', 'lelleswortheh@sogou.com', '7692 Mcbride Circle');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('19', 'Bowie', 'Rays', 'braysi@omniture.com', '114 Maple Street');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('20', 'Cate', 'Tourville', 'ctourvillej@linkedin.com', '1660 Lawn Street');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('21', 'Krissie', 'Lettsom', 'klettsomk@yolasite.com', '269 Lakewood Drive');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('22', 'Griffy', 'Flockhart', 'gflockhartl@sfgate.com', '79061 Steensland Plaza');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('23', 'Cad', 'Biaggioni', 'cbiaggionim@over-blog.com', '2788 Blaine Point');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('24', 'Berni', 'Kas', 'bkasn@europa.eu', '4 Sachs Point');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('25', 'Catherin', 'Shields', 'cshieldso@samsung.com', '7859 Kensington Hill');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('26', 'Crosby', 'Lovejoy', 'clovejoyp@liveinternet.ru', '7 Hoffman Crossing');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('27', 'Erhard', 'Elner', 'eelnerq@sun.com', '73 Trailsway Avenue');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('28', 'Coraline', 'Hadenton', 'chadentonr@yahoo.co.jp', '057 Petterle Circle');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('29', 'Reggie', 'Pimley', 'rpimleys@bandcamp.com', '1398 Marcy Plaza');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('30', 'Raleigh', 'Pursglove', 'rpursglovet@geocities.com', '1 Northview Lane');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('31', 'Emmet', 'Van Daalen', 'evandaalenu@yellowbook.com', '51 Dayton Drive');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('32', 'Sheeree', 'Bladen', 'sbladenv@hhs.gov', '47 Union Point');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('33', 'Florida', 'Gronow', 'fgronoww@imageshack.us', '669 Hansons Terrace');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('34', 'Dori', 'Drew-Clifton', 'ddrewcliftonx@smugmug.com', '1 Russell Parkway');
INSERT INTO customer (`user_id`, `firstname`, `lastname`, `email`, `address`) VALUES ('35', 'Hastings', 'Berston', 'hberstony@tmall.com', '8 Bonner Park');